packageNum: 617
packageIdent: knb-lter-cap.617.3
title: "Regional drinking water quality monitoring program: long-term monitoring of water quality in select canals, reservoirs, and treatment plants of the greater Phoenix, Arizona metropolitan area drinking water system, ongoing since 1998"
